#!/usr/bin/env bash
#
# gen_notice.sh — generate third-party license attribution manifests.
#
# Produces two files per ecosystem, mirroring the format npm's
# `license-checker` uses (NOTICE = summary tree, NOTICE.csv = per-package
# detail). For Rust it queries crates.io for each crate's SPDX license
# expression; for the frontend it shells out to `license-checker`.
#
# Why this exists: filebox statically links its Rust deps into a single
# binary, so the per-crate LICENSE files vanish from the artifact. The
# frontend is bundled by Vite and ships the same way. Wide licenses
# (MIT/Apache/BSD) literally require "include the license text in copies",
# so a NOTICE manifest is the lightweight way to stay compliant when
# distributing the release tarballs. See frontend/package.json + Cargo.lock.
#
# Usage:
#   ./scripts/gen_notice.sh              # both Rust + frontend
#   ./scripts/gen_notice.sh rust         # Rust only  -> ./NOTICE, ./NOTICE.csv
#   ./scripts/gen_notice.sh frontend     # frontend only -> frontend/NOTICE(.csv)
#   ./scripts/gen_notice.sh --help
#
# Requirements:
#   - python3 (stdlib only — urllib, json, re, concurrent.futures)
#   - npx (for the frontend; pulls license-checker on first run)
#   - network access to crates.io for Rust metadata
#
# Exit codes: 0 success, 1 bad usage / missing tool, 2 upstream query failure.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

usage() {
  cat <<'EOF' >&2
gen_notice.sh — generate third-party license attribution manifests.

Usage:
  ./scripts/gen_notice.sh              # Rust + frontend
  ./scripts/gen_notice.sh rust         # Cargo.lock only
  ./scripts/gen_notice.sh frontend     # package-lock.json only
  ./scripts/gen_notice.sh --help

Outputs:
  rust:     ./NOTICE  +  ./NOTICE.csv   (one row per third-party crate)
  frontend: frontend/NOTICE  +  frontend/NOTICE.csv

The project's own packages (filebox-*, frontend) are excluded from the
counts since they are MIT-licensed by the repo LICENSE.
EOF
}

# --------------------------------------------------------------------------- #
# Rust: parse Cargo.lock, query crates.io for each crate's SPDX license.
# --------------------------------------------------------------------------- #
gen_rust() {
  local lockfile="Cargo.lock"
  [ -f "$lockfile" ] || { echo "gen_notice: $lockfile not found" >&2; exit 1; }

  python3 - "$lockfile" <<'PY'
import json, re, sys, urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

lockfile = sys.argv[1]
text = open(lockfile).read()
# Cargo.lock packages look like [[package]]\n name = "x"\n version = "y"
crates = []
for m in re.finditer(
    r'\[\[package\]\]\s*name\s*=\s*"([^"]+)"\s*version\s*=\s*"([^"]+)"', text):
    name, ver = m.group(1), m.group(2)
    # Skip workspace-internal crates (filebox-hub, filebox-agent, filebox-protocol).
    if name.startswith("filebox"):
        continue
    crates.append((name, ver))

if not crates:
    print("gen_notice: no third-party crates found in", lockfile, file=sys.stderr)
    sys.exit(1)

def fetch(nv):
    name, ver = nv
    url = f"https://crates.io/api/v1/crates/{name}/{ver}"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "filebox-gen-notice"})
        d = json.load(urllib.request.urlopen(req, timeout=20))
        lic = d.get("version", {}).get("license") or "(unknown)"
        return (name, ver, lic)
    except Exception as e:
        # Don't fail the whole run on one bad query — record and continue.
        print(f"  warning: {name}@{ver}: {e}", file=sys.stderr)
        return (name, ver, "(error)")

results = []
with ThreadPoolExecutor(max_workers=8) as ex:
    futs = {ex.submit(fetch, nv): nv for nv in crates}
    done = 0
    for f in as_completed(futs):
        results.append(f.result())
        done += 1
        if done % 50 == 0:
            print(f"  rust: {done}/{len(crates)}", file=sys.stderr, flush=True)

errors = [r for r in results if r[2] == "(error)"]
unknown = [r for r in results if r[2] == "(unknown)"]

license_count = {}
for _, _, lic in results:
    license_count[lic] = license_count.get(lic, 0) + 1

with open("NOTICE", "w") as f:
    f.write("Third-party license summary for Rust dependencies (Cargo.lock).\n")
    f.write("This file is auto-generated by scripts/gen_notice.sh.\n")
    f.write("The project itself (filebox) is MIT-licensed and excluded.\n\n")
    for lic in sorted(license_count, key=lambda k: (-license_count[k], k)):
        f.write(f"├─ {lic}: {license_count[lic]}\n")
    if errors or unknown:
        f.write("\nNOTE: entries marked (error)/(unknown) need manual review.\n")

with open("NOTICE.csv", "w") as f:
    f.write('"crate","version","license"\n')
    for name, ver, lic in sorted(results):
        q = lambda s: '"' + str(s).replace('"', '""') + '"'
        f.write(f"{q(name)},{q(ver)},{q(lic)}\n")

print(f"rust: {len(results)} crates -> NOTICE, NOTICE.csv", file=sys.stderr)
if errors:
    print(f"rust: {len(errors)} crates failed to query (marked in output)", file=sys.stderr)
if unknown:
    print(f"rust: {len(unknown)} crates have no license field (marked in output)", file=sys.stderr)
# Non-fatal: even with a few (error)/(unknown) the manifest is still useful.
# Exit 2 only if a large fraction failed.
if len(errors) > len(results) * 0.1:
    sys.exit(2)
PY
}

# --------------------------------------------------------------------------- #
# Frontend: delegate to license-checker via npx, then strip the root-package
# UNLICENSED noise (license-checker misreports private:true packages).
# --------------------------------------------------------------------------- #
gen_frontend() {
  local pkgdir="frontend"
  [ -f "$pkgdir/package-lock.json" ] || { echo "gen_notice: $pkgdir/package-lock.json not found" >&2; exit 1; }

  echo "frontend: querying via license-checker (npx)..." >&2
  (cd "$pkgdir" && npx --yes license-checker --production --summary --out NOTICE 2>/dev/null)
  (cd "$pkgdir" && npx --yes license-checker --production --csv --out NOTICE.csv 2>/dev/null)

  # license-checker hard-reports the root package as UNLICENSED when
  # private:true is set, ignoring the license field. Strip that row so the
  # manifest reflects only real third-party packages.
  if [ -f "$pkgdir/NOTICE.csv" ]; then
    grep -v '^"frontend@0\.0\.0"' "$pkgdir/NOTICE.csv" > "$pkgdir/NOTICE.csv.tmp" \
      && mv "$pkgdir/NOTICE.csv.tmp" "$pkgdir/NOTICE.csv"
  fi

  # Add a clarifying header to the summary.
  if [ -f "$pkgdir/NOTICE" ]; then
    {
      echo "Third-party license summary (production dependencies only)."
      echo "Auto-generated by scripts/gen_notice.sh via license-checker."
      echo "The project itself (frontend) is MIT-licensed and excluded."
      echo
      cat "$pkgdir/NOTICE"
    } > "$pkgdir/NOTICE.tmp" && mv "$pkgdir/NOTICE.tmp" "$pkgdir/NOTICE"
  fi

  local n
  n=$(($(wc -l < "$pkgdir/NOTICE.csv") - 1))
  echo "frontend: $n packages -> frontend/NOTICE, frontend/NOTICE.csv" >&2
}

# --------------------------------------------------------------------------- #
target="${1:-all}"
case "$target" in
  -h|--help) usage; exit 0 ;;
  rust)    gen_rust ;;
  frontend) gen_frontend ;;
  all)     gen_rust; gen_frontend ;;
  *) echo "gen_notice: unknown target '$target' (try: rust, frontend, all, --help)" >&2; exit 1 ;;
esac

echo "done." >&2
